//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessStatu
    {
        public long AccessStatusSer { get; set; }
        public long PatientSer { get; set; }
        public byte[] TimeStamp { get; set; }
        public string TypeOfTimeStamp { get; set; }
        public string UserName { get; set; }
        public string TaskName { get; set; }
        public string WorkStationName { get; set; }
        public Nullable<int> ExtModified { get; set; }
        public string ExtTaskName { get; set; }
        public string ExtUserName { get; set; }
        public string ExtWorkstation { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
