//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActCaptDiagnosisMH
    {
        public long ActCaptDiagnosisSer { get; set; }
        public int ActCaptDiagnosisRevCount { get; set; }
        public long ActivityCaptureSer { get; set; }
        public int ActivityCaptureRevCount { get; set; }
        public long DiagnosisSer { get; set; }
        public string LastKnownDiagnosisId { get; set; }
        public string LastKnownDiagnosisTableName { get; set; }
        public string LastKnownDiagnosisCode { get; set; }
        public string ObjectStatus { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public Nullable<int> ClsSchemeId { get; set; }
    
        public virtual ActCaptDiagnosi ActCaptDiagnosi { get; set; }
    }
}
