//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityInstanceLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityInstanceLink()
        {
            this.ActivityInstanceLinkMHs = new HashSet<ActivityInstanceLinkMH>();
        }
    
        public long ActivityInstanceLinkSer { get; set; }
        public int ActivityInstanceLinkRevCount { get; set; }
        public long ActivityInstanceSer { get; set; }
        public long PredecessorSer { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual ActivityInstance ActivityInstance { get; set; }
        public virtual ActivityInstance ActivityInstance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityInstanceLinkMH> ActivityInstanceLinkMHs { get; set; }
    }
}
