//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityCapture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityCapture()
        {
            this.ActCaptDiagnosis = new HashSet<ActCaptDiagnosi>();
            this.ActCaptTreatments = new HashSet<ActCaptTreatment>();
            this.ActivityCaptureAttributes = new HashSet<ActivityCaptureAttribute>();
            this.ActivityCaptureMHs = new HashSet<ActivityCaptureMH>();
            this.BillSysChrgWrks = new HashSet<BillSysChrgWrk>();
            this.Credits = new HashSet<Credit>();
        }
    
        public long ActivityCaptureSer { get; set; }
        public int ActivityCaptureRevCount { get; set; }
        public long ActivityInstanceSer { get; set; }
        public int ActivityInstanceRevCount { get; set; }
        public Nullable<long> AccountBillingCodeSer { get; set; }
        public Nullable<int> AccountBillingCodeRevCount { get; set; }
        public Nullable<long> PatientPayorSer { get; set; }
        public Nullable<int> PatientPayorRevCount { get; set; }
        public Nullable<long> PayorSer { get; set; }
        public Nullable<long> ResourceSer { get; set; }
        public Nullable<long> AttendingOncologistSer { get; set; }
        public Nullable<long> DepartmentSer { get; set; }
        public Nullable<long> CourseSer { get; set; }
        public string LastKnownCourseId { get; set; }
        public int InPatientFlag { get; set; }
        public string PatientStatus { get; set; }
        public string CompletionResetBy { get; set; }
        public string Comment { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActCaptDiagnosi> ActCaptDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActCaptTreatment> ActCaptTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityCaptureAttribute> ActivityCaptureAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityCaptureMH> ActivityCaptureMHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSysChrgWrk> BillSysChrgWrks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credit> Credits { get; set; }
        public virtual ActivityInstance ActivityInstance { get; set; }
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Doctor Doctor1 { get; set; }
        public virtual Payor Payor { get; set; }
    }
}
