//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityPttrnResrc
    {
        public long ActivityPttrnSer { get; set; }
        public long ResourceSer { get; set; }
        public int ExclusiveFlag { get; set; }
        public int PrimaryFlag { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual ActivityPttrn ActivityPttrn { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
