//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityPttrn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityPttrn()
        {
            this.ActivityPttrnPerCycles = new HashSet<ActivityPttrnPerCycle>();
            this.ActivityPttrnResrcs = new HashSet<ActivityPttrnResrc>();
        }
    
        public long ActivityPttrnSer { get; set; }
        public Nullable<long> DepartmentSer { get; set; }
        public Nullable<long> ActivitySer { get; set; }
        public Nullable<System.DateTime> PatternStartDateTime { get; set; }
        public Nullable<System.DateTime> PatternEndDateTime { get; set; }
        public Nullable<int> WeeksPerCycle { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityPttrnPerCycle> ActivityPttrnPerCycles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityPttrnResrc> ActivityPttrnResrcs { get; set; }
        public virtual Department Department { get; set; }
    }
}
