//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicator()
        {
            this.ApplicatorJawSizes = new HashSet<ApplicatorJawSize>();
        }
    
        public long AddOnSer { get; set; }
        public int AllowInserts { get; set; }
        public int RectangularFlag { get; set; }
        public Nullable<double> FieldSizeX { get; set; }
        public Nullable<double> FieldSizeY { get; set; }
        public Nullable<double> ApplicatorLength { get; set; }
        public string ApplicatorDICOMType { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicatorJawSize> ApplicatorJawSizes { get; set; }
    }
}
