//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attendee()
        {
            this.AttendeeMHs = new HashSet<AttendeeMH>();
            this.ReminderAcks = new HashSet<ReminderAck>();
            this.ScheduledProcedures = new HashSet<ScheduledProcedure>();
        }
    
        public long AttendeeSer { get; set; }
        public int AttendeeRevCount { get; set; }
        public long ActivityInstanceSer { get; set; }
        public int ActivityInstanceRevCount { get; set; }
        public Nullable<long> ResourceSer { get; set; }
        public Nullable<long> ResourceGroupSer { get; set; }
        public string ObjectStatus { get; set; }
        public int ExclusiveFlag { get; set; }
        public int PrimaryFlag { get; set; }
        public string ParticipationRole { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public int ActivityOwnerFlag { get; set; }
    
        public virtual ActivityInstance ActivityInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendeeMH> AttendeeMHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReminderAck> ReminderAcks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledProcedure> ScheduledProcedures { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ResourceGroup ResourceGroup { get; set; }
    }
}
