//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auxiliary
    {
        public long ResourceSer { get; set; }
        public string AuxiliaryId { get; set; }
        public string AuxiliaryName { get; set; }
        public string AuxiliaryCode { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
}
