//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicWedge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DynamicWedge()
        {
            this.STTFiles = new HashSet<STTFile>();
        }
    
        public long AddOnSer { get; set; }
        public int EnhancedFlag { get; set; }
        public int TreatmentFlag { get; set; }
        public int BaseFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STTFile> STTFiles { get; set; }
        public virtual Wedge Wedge { get; set; }
    }
}
