//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public long EmployerSer { get; set; }
        public Nullable<long> AddressSer { get; set; }
        public long PatientSer { get; set; }
        public string EmployerId { get; set; }
        public string EmployerName { get; set; }
        public int PrimaryFlag { get; set; }
        public string DivisionName { get; set; }
        public string POCName { get; set; }
        public string Comment { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public int SchoolFlag { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
