//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorMsg
    {
        public int ErrorCode { get; set; }
        public string LanguageId { get; set; }
        public string ErrorLabel { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorDescription { get; set; }
    
        public virtual LanguageLookup LanguageLookup { get; set; }
    }
}
