//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalIntegration
    {
        public long ExternalIntegrationSer { get; set; }
        public string VarisType { get; set; }
        public long VarisSer { get; set; }
        public string ExternalApplication { get; set; }
        public string ExternalID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string AuthenticationID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string AdditionalInfo { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    }
}
