//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalFieldCommon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalFieldCommon()
        {
            this.Blocks = new HashSet<Block>();
            this.Compensators = new HashSet<Compensator>();
            this.ControlPoints = new HashSet<ControlPoint>();
            this.FieldAddOns = new HashSet<FieldAddOn>();
            this.FieldStructures = new HashSet<FieldStructure>();
            this.MLCPlans = new HashSet<MLCPlan>();
            this.RefWaveformFields = new HashSet<RefWaveformField>();
            this.TrackingFields = new HashSet<TrackingField>();
        }
    
        public long RadiationSer { get; set; }
        public Nullable<double> Meterset { get; set; }
        public Nullable<double> MetersetPerGy { get; set; }
        public Nullable<double> TreatmentTime { get; set; }
        public int SetupFieldFlag { get; set; }
        public string MotionCompSource { get; set; }
        public string MotionCompTechnique { get; set; }
        public string SetupTechnique { get; set; }
        public Nullable<double> SSD { get; set; }
        public Nullable<double> SourceFieldEntryDistance { get; set; }
        public Nullable<double> CouchLat { get; set; }
        public Nullable<double> CouchLatDelta { get; set; }
        public Nullable<double> CouchLng { get; set; }
        public Nullable<double> CouchLngDelta { get; set; }
        public Nullable<double> CouchVrt { get; set; }
        public Nullable<double> CouchVrtDelta { get; set; }
        public Nullable<double> PatientSupportAngle { get; set; }
        public double TableTopPitchAngle { get; set; }
        public double TableTopRollAngle { get; set; }
        public Nullable<double> IDUPosLat { get; set; }
        public Nullable<double> IDUPosLng { get; set; }
        public Nullable<double> IDUPosVrt { get; set; }
        public Nullable<double> IDURtn { get; set; }
        public Nullable<double> IsoCenterPositionX { get; set; }
        public Nullable<double> IsoCenterPositionY { get; set; }
        public Nullable<double> IsoCenterPositionZ { get; set; }
        public Nullable<long> TechniqueSer { get; set; }
        public Nullable<long> EnergyModeSer { get; set; }
        public Nullable<long> ToleranceSer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Block> Blocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compensator> Compensators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlPoint> ControlPoints { get; set; }
        public virtual EnergyMode EnergyMode { get; set; }
        public virtual ExternalField ExternalField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldAddOn> FieldAddOns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldStructure> FieldStructures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MLCPlan> MLCPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefWaveformField> RefWaveformFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingField> TrackingFields { get; set; }
        public virtual Radiation Radiation { get; set; }
        public virtual Technique Technique { get; set; }
        public virtual Tolerance Tolerance { get; set; }
    }
}
