//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldProton
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FieldProton()
        {
            this.FieldProton1 = new HashSet<FieldProton>();
        }
    
        public long RadiationSer { get; set; }
        public Nullable<double> AirGap { get; set; }
        public string FieldModifiersSet { get; set; }
        public Nullable<double> DistalEndDistance { get; set; }
        public Nullable<double> DistalEndEnergy { get; set; }
        public int IsocenterMarginFlag { get; set; }
        public Nullable<long> PrimaryRadiationSer { get; set; }
        public Nullable<double> ProximalEndDistance { get; set; }
        public int SnoutPositionInputFlag { get; set; }
        public Nullable<double> TargetUncertaintyMarginX1 { get; set; }
        public Nullable<double> TargetUncertaintyMarginX2 { get; set; }
        public Nullable<double> TargetUncertaintyMarginY1 { get; set; }
        public Nullable<double> TargetUncertaintyMarginY2 { get; set; }
        public double VirtualSADX { get; set; }
        public double VirtualSADY { get; set; }
        public string BeamCurrModulationId { get; set; }
        public string BeamlineDataTableVers { get; set; }
        public string BeamlineSettingsId { get; set; }
        public Nullable<double> SOBPWidth { get; set; }
        public Nullable<double> HeadFixationAngle { get; set; }
        public Nullable<double> FixLightPolarPos { get; set; }
        public Nullable<double> FixLightAzimuthAngle { get; set; }
        public Nullable<double> WedgeOrientation { get; set; }
        public Nullable<double> WedgeThinEdgePos { get; set; }
        public int Status { get; set; }
        public Nullable<double> SnoutFitPosition { get; set; }
        public short UserPreselectedSOBP { get; set; }
        public short UserPreselectedRange { get; set; }
        public string SpotListFile { get; set; }
        public Nullable<short> ScanningTechnique { get; set; }
    
        public virtual ExternalField ExternalField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldProton> FieldProton1 { get; set; }
        public virtual FieldProton FieldProton2 { get; set; }
    }
}
