//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTAScheduledTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LTAScheduledTask()
        {
            this.LTAScheduledTaskPatients = new HashSet<LTAScheduledTaskPatient>();
        }
    
        public long ScheduledTaskSer { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public long ArchiveLocationSer { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public string StatusDescription { get; set; }
    
        public virtual ArchiveLocation ArchiveLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LTAScheduledTaskPatient> LTAScheduledTaskPatients { get; set; }
    }
}
