//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingLimit
    {
        public long OperatingLimitSer { get; set; }
        public long ResourceSer { get; set; }
        public string ParameterType { get; set; }
        public string ParameterName { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public Nullable<double> DefValue { get; set; }
        public Nullable<int> LimitPrecision { get; set; }
        public Nullable<int> TolerancePossible { get; set; }
        public string MotionMode { get; set; }
        public Nullable<double> MaxSpeed { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public Nullable<long> PrimaryFluenceModeSer { get; set; }
        public Nullable<long> TechniqueSer { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual PrimaryFluenceMode PrimaryFluenceMode { get; set; }
        public virtual Technique Technique { get; set; }
    }
}
