//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatEdHstryRelevance
    {
        public long PatEdHstryRelevanceSer { get; set; }
        public string TableName { get; set; }
        public string AttribName { get; set; }
        public string AfterTreatInd { get; set; }
        public string AfterApproveInd { get; set; }
        public int AttribRelevanceInd { get; set; }
        public int RowRelevanceInd { get; set; }
        public int OnInsInd { get; set; }
        public int OnUpdInd { get; set; }
        public int OnDelInd { get; set; }
    }
}
