//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.AccessStatus = new HashSet<AccessStatu>();
            this.AccountBillingCodes = new HashSet<AccountBillingCode>();
            this.ADT08 = new HashSet<ADT08>();
            this.ArchiveRestoredFiles = new HashSet<ArchiveRestoredFile>();
            this.BillSysChrgWrks = new HashSet<BillSysChrgWrk>();
            this.BillSysSentCharges = new HashSet<BillSysSentCharge>();
            this.ChartQAs = new HashSet<ChartQA>();
            this.Courses = new HashSet<Course>();
            this.DoseMatrices = new HashSet<DoseMatrix>();
            this.Employers = new HashSet<Employer>();
            this.Images = new HashSet<Image>();
            this.Image4D = new HashSet<Image4D>();
            this.InVivoDosimetries = new HashSet<InVivoDosimetry>();
            this.LTAScheduledTaskPatients = new HashSet<LTAScheduledTaskPatient>();
            this.NonScheduledActivities = new HashSet<NonScheduledActivity>();
            this.ObsoleteObjects = new HashSet<ObsoleteObject>();
            this.PatientAddresses = new HashSet<PatientAddress>();
            this.PatientDepartments = new HashSet<PatientDepartment>();
            this.PatientDirectives = new HashSet<PatientDirective>();
            this.PatientDoctors = new HashSet<PatientDoctor>();
            this.PatientEditingLogs = new HashSet<PatientEditingLog>();
            this.PatientHospitals = new HashSet<PatientHospital>();
            this.PatientNotes = new HashSet<PatientNote>();
            this.PatientPayors = new HashSet<PatientPayor>();
            this.PatientRTStatus = new HashSet<PatientRTStatu>();
            this.PatientStaffs = new HashSet<PatientStaff>();
            this.PatientTransportations = new HashSet<PatientTransportation>();
            this.PatientVolumes = new HashSet<PatientVolume>();
            this.Photos = new HashSet<Photo>();
            this.PointOfContacts = new HashSet<PointOfContact>();
            this.ScheduledActivities = new HashSet<ScheduledActivity>();
            this.Studies = new HashSet<Study>();
            this.Templates = new HashSet<Template>();
            this.TrackingInformations = new HashSet<TrackingInformation>();
            this.TreatmentRecords = new HashSet<TreatmentRecord>();
        }
    
        public long PatientSer { get; set; }
        public string PatientId { get; set; }
        public string PatientId2 { get; set; }
        public string PatientUID { get; set; }
        public string PatientType { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationUserName { get; set; }
        public string SSN { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NameSuffix { get; set; }
        public string Honorific { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Sex { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhone { get; set; }
        public string Citizenship { get; set; }
        public string Race { get; set; }
        public string BirthCountry { get; set; }
        public string BirthState { get; set; }
        public string BirthCounty { get; set; }
        public string BirthCity { get; set; }
        public string PatientIdIssuer { get; set; }
        public string MaidenName { get; set; }
        public string MothersMaidenName { get; set; }
        public string MedRecordLocator { get; set; }
        public string Language { get; set; }
        public string Occupation { get; set; }
        public string SpecialNeeds { get; set; }
        public string ReligiousPreference { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public string ArchiveVolume { get; set; }
        public string Comment { get; set; }
        public int ClinicalTrialFlag { get; set; }
        public string FileDataSiteID { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public string MobilePhone { get; set; }
        public string Ethnicity { get; set; }
        public Nullable<long> MobilePhoneProviderSer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessStatu> AccessStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountBillingCode> AccountBillingCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADT08> ADT08 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchiveRestoredFile> ArchiveRestoredFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSysChrgWrk> BillSysChrgWrks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSysSentCharge> BillSysSentCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartQA> ChartQAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoseMatrix> DoseMatrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employer> Employers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image4D> Image4D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InVivoDosimetry> InVivoDosimetries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LTAScheduledTaskPatient> LTAScheduledTaskPatients { get; set; }
        public virtual MobilePhoneProvider MobilePhoneProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonScheduledActivity> NonScheduledActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObsoleteObject> ObsoleteObjects { get; set; }
        public virtual PatientActual PatientActual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAddress> PatientAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDepartment> PatientDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDirective> PatientDirectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDoctor> PatientDoctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientEditingLog> PatientEditingLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientHospital> PatientHospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientNote> PatientNotes { get; set; }
        public virtual PatientParticular PatientParticular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientPayor> PatientPayors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientRTStatu> PatientRTStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientStaff> PatientStaffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientTransportation> PatientTransportations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientVolume> PatientVolumes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointOfContact> PointOfContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledActivity> ScheduledActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Study> Studies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Template> Templates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingInformation> TrackingInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentRecord> TreatmentRecords { get; set; }
    }
}
