//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalMaterial
    {
        public long PhysicalMaterialSer { get; set; }
        public string PhysicalMaterialId { get; set; }
        public double DefaultMassDensity { get; set; }
        public Nullable<double> MinimumMassDensity { get; set; }
        public Nullable<double> MaximumMassDensity { get; set; }
        public int LookupFlag { get; set; }
        public int ReadOnlyFlag { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public string PhysicalMaterialVersion { get; set; }
    }
}
