//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSetupStructureModelStructure
    {
        public long PlanSetupSer { get; set; }
        public long StructureSer { get; set; }
        public System.Guid PlanningModelLibraryStructureGuid { get; set; }
        public string StructureType { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual PlanSetup PlanSetup { get; set; }
        public virtual Structure Structure { get; set; }
    }
}
