//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanConcurrency
    {
        public string PlanUID { get; set; }
        public byte[] LastSaveCRC { get; set; }
        public byte[] LastITLoadCRC { get; set; }
        public int CheckSumSource { get; set; }
        public Nullable<System.DateTime> UserDecidedAbortPartialOnDate { get; set; }
    }
}
