//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionTemplateProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrescriptionTemplateProperty()
        {
            this.PrescriptionTemplatePropertyItems = new HashSet<PrescriptionTemplatePropertyItem>();
        }
    
        public long PrescriptionTemplatePropertySer { get; set; }
        public string PrescriptionPropertyTemplateName { get; set; }
        public Nullable<long> PrescriptionTemplateSer { get; set; }
        public short PropertyType { get; set; }
        public string PropertyValue { get; set; }
        public string UserCUID { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual PrescriptionTemplate PrescriptionTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionTemplatePropertyItem> PrescriptionTemplatePropertyItems { get; set; }
    }
}
