//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrescriptionTemplate()
        {
            this.Prescriptions = new HashSet<Prescription>();
            this.PrescriptionTemplateAnatomies = new HashSet<PrescriptionTemplateAnatomy>();
            this.PrescriptionTemplateProperties = new HashSet<PrescriptionTemplateProperty>();
        }
    
        public long PrescriptionTemplateSer { get; set; }
        public string PrescriptionTemplateName { get; set; }
        public string PrescriptionName { get; set; }
        public string Intent { get; set; }
        public string UserCUID { get; set; }
        public string Gating { get; set; }
        public Nullable<int> SimulationNeeded { get; set; }
        public string BolusFrequency { get; set; }
        public string BolusThickness { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public string PhaseType { get; set; }
        public Nullable<int> NumberOfFractions { get; set; }
        public string Technique { get; set; }
        public string Site { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreationUserName { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionTemplateAnatomy> PrescriptionTemplateAnatomies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionTemplateProperty> PrescriptionTemplateProperties { get; set; }
    }
}
