//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureItemResource
    {
        public long ProcedureItemResourceSer { get; set; }
        public long ProcedureItemSer { get; set; }
        public Nullable<long> ResourceSer { get; set; }
        public Nullable<long> ResourceGroupSer { get; set; }
        public string Modality { get; set; }
        public int NoEditFlag { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual ProcedureItem ProcedureItem { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ResourceGroup ResourceGroup { get; set; }
    }
}
