//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiationHstry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RadiationHstry()
        {
            this.ActCaptTreatments = new HashSet<ActCaptTreatment>();
            this.ChartQATreatments = new HashSet<ChartQATreatment>();
            this.RefPointHstries = new HashSet<RefPointHstry>();
        }
    
        public long RadiationHstrySer { get; set; }
        public long TreatmentRecordSer { get; set; }
        public string RadiationHstryType { get; set; }
        public string TreatmentDeliveryType { get; set; }
        public long RadiationSer { get; set; }
        public string RadiationId { get; set; }
        public string RadiationName { get; set; }
        public Nullable<int> RadiationNumber { get; set; }
        public string TechniqueLabel { get; set; }
        public string RadiationType { get; set; }
        public System.DateTime TreatmentStartTime { get; set; }
        public System.DateTime TreatmentEndTime { get; set; }
        public Nullable<double> TreatmentTime { get; set; }
        public byte TreatmentTimeOverrideFlag { get; set; }
        public string TerminationStatus { get; set; }
        public int FractionNumber { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalUserName { get; set; }
        public string UserName1 { get; set; }
        public string UserName2 { get; set; }
        public string UserName3 { get; set; }
        public int OverrideFlag { get; set; }
        public Nullable<int> NoOfImage { get; set; }
        public int PrintFlag { get; set; }
        public byte RVFlag { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
        public string HistoryNote { get; set; }
        public string MachineNote { get; set; }
        public string FieldSetupNote { get; set; }
        public string BeamOffCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActCaptTreatment> ActCaptTreatments { get; set; }
        public virtual BrachyFieldHstry BrachyFieldHstry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartQATreatment> ChartQATreatments { get; set; }
        public virtual ExternalFieldCommonHstry ExternalFieldCommonHstry { get; set; }
        public virtual Radiation Radiation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefPointHstry> RefPointHstries { get; set; }
        public virtual TreatmentRecord TreatmentRecord { get; set; }
    }
}
