//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.Report1 = new HashSet<Report>();
            this.ReportLinkages = new HashSet<ReportLinkage>();
            this.ReportLinkages1 = new HashSet<ReportLinkage>();
            this.ReportParameters = new HashSet<ReportParameter>();
        }
    
        public long ReportSer { get; set; }
        public long AppUserSer { get; set; }
        public string ReportName { get; set; }
        public Nullable<long> DerivedFromReportSer { get; set; }
        public string ProcedureName { get; set; }
        public string Description { get; set; }
        public string ReportCategory { get; set; }
        public string ReportAccess { get; set; }
        public string ReportType { get; set; }
        public string FSRptFileName { get; set; }
        public string FSSchFileName { get; set; }
        public string SchemaName { get; set; }
        public string ReportFileName { get; set; }
        public string LanguageId { get; set; }
        public int EditFlag { get; set; }
        public int EnabledFlag { get; set; }
        public string ReportVersion { get; set; }
        public string SchemaVersion { get; set; }
        public string ReportValidation { get; set; }
        public string DerivedFromReportVersion { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public int ProcedureDatabaseType { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report1 { get; set; }
        public virtual Report Report2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportLinkage> ReportLinkages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportLinkage> ReportLinkages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportParameter> ReportParameters { get; set; }
    }
}
