//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledProcedure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduledProcedure()
        {
            this.ScheduledObjectPointers = new HashSet<ScheduledObjectPointer>();
            this.ScheduledPerformedProcedures = new HashSet<ScheduledPerformedProcedure>();
            this.ScheduledProcedureItems = new HashSet<ScheduledProcedureItem>();
        }
    
        public long ScheduledProcedureSer { get; set; }
        public long ActivityInstanceSer { get; set; }
        public int ActivityInstanceRevCount { get; set; }
        public Nullable<long> AttendeeSer { get; set; }
        public Nullable<int> AttendeeRevCount { get; set; }
        public string Status { get; set; }
        public string ScheduledProcedureUID { get; set; }
        public string ScheduledProcedureId { get; set; }
        public Nullable<System.DateTime> ScheduledStartDateTime { get; set; }
        public Nullable<System.DateTime> ScheduledEndDateTime { get; set; }
        public int ExportedFlag { get; set; }
        public string Priority { get; set; }
        public string InputAvailability { get; set; }
        public string ProcedureStepLabel { get; set; }
        public string WorklistLabel { get; set; }
        public string ObjectStatus { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual ActivityInstance ActivityInstance { get; set; }
        public virtual Attendee Attendee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledObjectPointer> ScheduledObjectPointers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledPerformedProcedure> ScheduledPerformedProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledProcedureItem> ScheduledProcedureItems { get; set; }
    }
}
