//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionProcedureTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionProcedureTemplate()
        {
            this.SessionProcedureTemplateParts = new HashSet<SessionProcedureTemplatePart>();
        }
    
        public long SessionProcedureTemplateSer { get; set; }
        public string SessionProcedureTemplateId { get; set; }
        public string SessionProcedureTemplateName { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationUser { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionProcedureTemplatePart> SessionProcedureTemplateParts { get; set; }
    }
}
