//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotAddOn
    {
        public long AddOnSer { get; set; }
        public long SlotSer { get; set; }
        public Nullable<long> CacheKeySer { get; set; }
        public int DefaultFlag { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual Slot Slot { get; set; }
    }
}
