//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpatialRegistrationImage
    {
        public long SpatialRegistrationImageSer { get; set; }
        public long SpatialRegistrationSer { get; set; }
        public Nullable<long> ImageSer { get; set; }
        public string ImageClassUID { get; set; }
        public string ImageInstanceUID { get; set; }
        public string StudyUID { get; set; }
        public string SeriesUID { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual SpatialRegistration SpatialRegistration { get; set; }
    }
}
