//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardWedge
    {
        public long AddOnSer { get; set; }
        public Nullable<int> MotorizedFlag { get; set; }
        public Nullable<double> SourceWedgeDist { get; set; }
        public int OmniWedgeFlag { get; set; }
    
        public virtual Wedge Wedge { get; set; }
    }
}
