//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMH
    {
        public long TemplateSer { get; set; }
        public int TemplateRevCount { get; set; }
        public Nullable<long> PatientSer { get; set; }
        public Nullable<long> DiagnosisStageSer { get; set; }
        public Nullable<long> PayorSer { get; set; }
        public Nullable<long> ResourceSer { get; set; }
        public Nullable<long> DepartmentSer { get; set; }
        public Nullable<long> DerivedFromSer { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string TemplateID { get; set; }
        public Nullable<long> CourseSer { get; set; }
        public string ObjectStatus { get; set; }
        public int DefaultFlag { get; set; }
        public string Comment { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
