//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateCycleMH
    {
        public long TemplateCycleSer { get; set; }
        public int TemplateCycleRevCount { get; set; }
        public long TemplateSer { get; set; }
        public int TemplateRevCount { get; set; }
        public string ObjectStatus { get; set; }
        public long CycleSer { get; set; }
        public string Comment { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual TemplateCycle TemplateCycle { get; set; }
    }
}
