//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_TRTEventsCorrelated
    {
        public long RadiationHstrySer { get; set; }
        public Nullable<System.DateTime> TreatmentStartTime { get; set; }
        public Nullable<int> IsImage { get; set; }
        public Nullable<int> FractionNumber { get; set; }
        public Nullable<int> FractionNumberCalc { get; set; }
        public Nullable<int> EventNumber { get; set; }
        public Nullable<int> CorrelatedEventNumber { get; set; }
        public Nullable<int> LastFractionNumber { get; set; }
        public Nullable<int> LastFractionNumberCalc { get; set; }
        public Nullable<int> LastEventNumber { get; set; }
        public Nullable<int> LastCorrelatedEventNumber { get; set; }
        public long RTPlanSer { get; set; }
        public long FirstRTPlanSer { get; set; }
        public long PatientSer { get; set; }
    }
}
