//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venue()
        {
            this.PatientLocations = new HashSet<PatientLocation>();
            this.ResourceVenues = new HashSet<ResourceVenue>();
        }
    
        public long ResourceSer { get; set; }
        public string VenueId { get; set; }
        public string VenueType { get; set; }
        public string VenueName { get; set; }
        public string VenueDirections { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<int> ScheduleFlag { get; set; }
        public string EquipmentList { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientLocation> PatientLocations { get; set; }
        public virtual Resource Resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceVenue> ResourceVenues { get; set; }
    }
}
