//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriaQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedge
    {
        public long AddOnSer { get; set; }
        public string WedgeType { get; set; }
        public Nullable<double> WedgeAngle { get; set; }
        public int ThinEdgeToX1Flag { get; set; }
        public int ThinEdgeToX2Flag { get; set; }
        public int ThinEdgeToY1Flag { get; set; }
        public int ThinEdgeToY2Flag { get; set; }
        public Nullable<double> MaxCollX { get; set; }
        public Nullable<double> MinCollX { get; set; }
        public Nullable<double> MaxCollY { get; set; }
        public Nullable<double> MinCollY { get; set; }
        public Nullable<double> MaxX1 { get; set; }
        public Nullable<double> MinX1 { get; set; }
        public Nullable<double> MaxY1 { get; set; }
        public Nullable<double> MinY1 { get; set; }
        public Nullable<double> MaxX2 { get; set; }
        public Nullable<double> MinX2 { get; set; }
        public Nullable<double> MaxY2 { get; set; }
        public Nullable<double> MinY2 { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual DynamicWedge DynamicWedge { get; set; }
        public virtual StandardWedge StandardWedge { get; set; }
    }
}
