//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ActivityChecklistItems = new HashSet<ActivityChecklistItem>();
            this.ActivityAssociations = new HashSet<ActivityAssociation>();
            this.ActivityAssociations1 = new HashSet<ActivityAssociation>();
            this.ActivityAttributes = new HashSet<ActivityAttribute>();
            this.ActivityInstances = new HashSet<ActivityInstance>();
            this.ActivityMHs = new HashSet<ActivityMH>();
            this.ActivityPttrns = new HashSet<ActivityPttrn>();
            this.ActivityToProcedureCodes = new HashSet<ActivityToProcedureCode>();
            this.ActivityToProcedureItems = new HashSet<ActivityToProcedureItem>();
            this.AvailPrefPttrnDetails = new HashSet<AvailPrefPttrnDetail>();
            this.AvailPrefWeeklyPttrns = new HashSet<AvailPrefWeeklyPttrn>();
            this.BillSysChrgWrks = new HashSet<BillSysChrgWrk>();
            this.PttrnRelatedNonSchActivities = new HashSet<PttrnRelatedNonSchActivity>();
        }
    
        public long ActivitySer { get; set; }
        public int ActivityRevCount { get; set; }
        public long ActivityCategorySer { get; set; }
        public string ActivityCode { get; set; }
        public string ActivityType { get; set; }
        public Nullable<long> DerivedFromActivitySer { get; set; }
        public Nullable<int> NoEditFlag { get; set; }
        public string ObjectStatus { get; set; }
        public Nullable<long> ResourceGroupSer { get; set; }
        public Nullable<int> DefaultDuration { get; set; }
        public int ExclusiveFlag { get; set; }
        public Nullable<int> NotificationPriorTime { get; set; }
        public int AssignableFlag { get; set; }
        public string Description { get; set; }
        public byte[] ForeGroundColor { get; set; }
        public byte[] Icon { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public Nullable<long> DICOMCodeValueSer { get; set; }
        public int NotificationPriorTimeFlag { get; set; }
        public Nullable<long> EscalationGroupSer { get; set; }
        public Nullable<long> TreatmentCycleSer { get; set; }
        public int ReviewFlag { get; set; }
        public Nullable<long> UpdCPResourceGroupSer { get; set; }
        public Nullable<long> UpdCPEscalationGroupSer { get; set; }
        public int AutoGenerateFlag { get; set; }
        public int NoAutoPostFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityChecklistItem> ActivityChecklistItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityAssociation> ActivityAssociations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityAssociation> ActivityAssociations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityAttribute> ActivityAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityInstance> ActivityInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityMH> ActivityMHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityPttrn> ActivityPttrns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityToProcedureCode> ActivityToProcedureCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityToProcedureItem> ActivityToProcedureItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailPrefPttrnDetail> AvailPrefPttrnDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailPrefWeeklyPttrn> AvailPrefWeeklyPttrns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillSysChrgWrk> BillSysChrgWrks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PttrnRelatedNonSchActivity> PttrnRelatedNonSchActivities { get; set; }
        public virtual ActivityCategory ActivityCategory { get; set; }
        public virtual DICOMCodeValue DICOMCodeValue { get; set; }
        public virtual ResourceGroup ResourceGroup { get; set; }
        public virtual ResourceGroup ResourceGroup1 { get; set; }
        public virtual ResourceGroup ResourceGroup2 { get; set; }
        public virtual ResourceGroup ResourceGroup3 { get; set; }
        public virtual TreatmentCycle TreatmentCycle { get; set; }
    }
}
