//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityChecklistItem
    {
        public long ActivityChecklistItemSer { get; set; }
        public long ActivitySer { get; set; }
        public long ChecklistItemSer { get; set; }
        public int SortOrder { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ChecklistItem ChecklistItem { get; set; }
    }
}
