//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityCategory()
        {
            this.Activities = new HashSet<Activity>();
            this.ProcedureCodes = new HashSet<ProcedureCode>();
            this.ActtyCatgryResrcTypes = new HashSet<ActtyCatgryResrcType>();
            this.AvailPrefPttrnDetails = new HashSet<AvailPrefPttrnDetail>();
            this.AvailPrefWeeklyPttrns = new HashSet<AvailPrefWeeklyPttrn>();
        }
    
        public long ActivityCategorySer { get; set; }
        public string ActivityCategoryCode { get; set; }
        public Nullable<long> DepartmentSer { get; set; }
        public Nullable<long> DerivedFromActCategorySer { get; set; }
        public Nullable<int> SchedulableFlag { get; set; }
        public Nullable<int> NoEditFlag { get; set; }
        public string ObjectStatus { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedureCode> ProcedureCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActtyCatgryResrcType> ActtyCatgryResrcTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailPrefPttrnDetail> AvailPrefPttrnDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailPrefWeeklyPttrn> AvailPrefWeeklyPttrns { get; set; }
        public virtual Department Department { get; set; }
    }
}
