//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityAttribute()
        {
            this.ActivityAttributeMHs = new HashSet<ActivityAttributeMH>();
            this.ActivityCaptureAttributes = new HashSet<ActivityCaptureAttribute>();
        }
    
        public long ActivityAttributeSer { get; set; }
        public int ActivityAttributeRevCount { get; set; }
        public long ActivitySer { get; set; }
        public int ActivityRevCount { get; set; }
        public long UserDefActAttrSer { get; set; }
        public int UserDefActAttrRevCount { get; set; }
        public string ObjectStatus { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityAttributeMH> ActivityAttributeMHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityCaptureAttribute> ActivityCaptureAttributes { get; set; }
        public virtual UserDefActAttr UserDefActAttr { get; set; }
    }
}
