//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationAccessLog
    {
        public long ApplicationAccessLogSer { get; set; }
        public int Spid { get; set; }
        public int Suid { get; set; }
        public string LoginName { get; set; }
        public string ApplicationName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string ExtraInfo { get; set; }
    }
}
