//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppObject
    {
        public long AppObjectSer { get; set; }
        public string ObjectName { get; set; }
        public string ObjectGroupName { get; set; }
        public string Description { get; set; }
        public int AddStatusFlag { get; set; }
        public int DeleteStatusFlag { get; set; }
        public int ApproveStatusFlag { get; set; }
        public int AccessStatusFlag { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    }
}
