//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public decimal ApprovalSer { get; set; }
        public int ApprovalRevCount { get; set; }
        public long TypeSer { get; set; }
        public Nullable<long> Type1Ser { get; set; }
        public Nullable<long> Type2Ser { get; set; }
        public Nullable<int> TypeRevCount { get; set; }
        public Nullable<int> Type1RevCount { get; set; }
        public Nullable<int> Type2RevCount { get; set; }
        public string ApprovalType { get; set; }
        public string Status { get; set; }
        public string StatusUserName { get; set; }
        public System.DateTime StatusDate { get; set; }
        public string Comment { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    }
}
