//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeMetaData
    {
        public int ID { get; set; }
        public string DatasetName { get; set; }
        public string DatasetAttributeName { get; set; }
        public string TableAttributeName { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> IsRealTime { get; set; }
    }
}
