//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguredEMT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfiguredEMT()
        {
            this.AddOnValidations = new HashSet<AddOnValidation>();
        }
    
        public long ConfiguredEMTSer { get; set; }
        public long TechniqueSer { get; set; }
        public long EnergyModeSer { get; set; }
        public Nullable<double> DefaultVirtualSADX { get; set; }
        public Nullable<double> DefaultVirtualSADY { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddOnValidation> AddOnValidations { get; set; }
        public virtual EnergyMode EnergyMode { get; set; }
        public virtual Technique Technique { get; set; }
    }
}
