//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTScanner
    {
        public long ResourceSer { get; set; }
        public string CalibrationFile { get; set; }
        public int DefaultFlag { get; set; }
    
        public virtual ImagingDevice ImagingDevice { get; set; }
    }
}
