//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCObjectPointerSery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DCObjectPointerSery()
        {
            this.ObjectPointers = new HashSet<ObjectPointer>();
        }
    
        public long DCObjectPointerSeriesSer { get; set; }
        public long DCObjectPointerStudySer { get; set; }
        public string Modality { get; set; }
        public string SeriesUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectPointer> ObjectPointers { get; set; }
        public virtual DCObjectPointerStudy DCObjectPointerStudy { get; set; }
    }
}
