//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DerivedInstanceUID
    {
        public long DerivedInstanceUIDSer { get; set; }
        public long SliceSer { get; set; }
        public string InstanceUID { get; set; }
    
        public virtual Slouse Slouse { get; set; }
    }
}
