//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICOMCodeMeaning
    {
        public long DICOMCodeMeaningSer { get; set; }
        public long DICOMCodeValueSer { get; set; }
        public string Meaning { get; set; }
        public string LanguageId { get; set; }
        public string DisplayName { get; set; }
    
        public virtual DICOMCodeValue DICOMCodeValue { get; set; }
    }
}
