//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoseRate
    {
        public long DoseRateSer { get; set; }
        public long EnergyModeSer { get; set; }
        public int DoseRateValue { get; set; }
        public Nullable<int> RepRate { get; set; }
        public Nullable<int> DefaultFlag { get; set; }
        public string Comment { get; set; }
        public Nullable<long> PrimaryFluenceModeSer { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public int DefPortalImagingFlag { get; set; }
        public int LowPortalImagingFlag { get; set; }
        public int ConeBeamFlag { get; set; }
    
        public virtual EnergyMode EnergyMode { get; set; }
        public virtual PrimaryFluenceMode PrimaryFluenceMode { get; set; }
    }
}
