//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportExportReference
    {
        public string ReferencedTable { get; set; }
        public string ReferencedColumn { get; set; }
        public string ReferencingTable { get; set; }
        public string ReferencingColumn { get; set; }
        public int Forward { get; set; }
        public int Reverse { get; set; }
    
        public virtual ImportExportColumn ImportExportColumn { get; set; }
        public virtual ImportExportColumn ImportExportColumn1 { get; set; }
    }
}
