//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportExportColumn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportExportColumn()
        {
            this.ImportExportReferences = new HashSet<ImportExportReference>();
            this.ImportExportReferences1 = new HashSet<ImportExportReference>();
        }
    
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public int CopyOnExport { get; set; }
        public int IncludeInDuplicateCheck { get; set; }
        public int IncludeInConflictCheck { get; set; }
        public string UseInRowMatching { get; set; }
        public int RenameOnConflict { get; set; }
        public string LookupTableListSelector { get; set; }
        public string ValueOnImport { get; set; }
        public string SpecialValue { get; set; }
        public string InsertionParameterName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportExportReference> ImportExportReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportExportReference> ImportExportReferences1 { get; set; }
        public virtual ImportExportTable ImportExportTable { get; set; }
    }
}
