//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntfTrgr
    {
        public long IntfTrgrSer { get; set; }
        public Nullable<int> FacId { get; set; }
        public string InstId { get; set; }
        public string MsgEvntTyp { get; set; }
        public string MsgTyp { get; set; }
        public string OrderTyp { get; set; }
        public string TrgrStatusInd { get; set; }
        public string IntfAppParmIdNoTrgr { get; set; }
        public string IntfAppParmIdTrgr { get; set; }
        public string UserId { get; set; }
        public string UserInstId { get; set; }
        public string AppCd { get; set; }
        public string KeyName1 { get; set; }
        public string KeyName2 { get; set; }
        public string KeyName3 { get; set; }
        public string KeyName4 { get; set; }
        public string KeyName5 { get; set; }
        public string KeyName6 { get; set; }
        public string KeyName7 { get; set; }
        public string KeyName8 { get; set; }
        public string KeyName9 { get; set; }
        public string KeyName10 { get; set; }
        public string KeyValue1 { get; set; }
        public string KeyValue2 { get; set; }
        public string KeyValue3 { get; set; }
        public string KeyValue4 { get; set; }
        public string KeyValue5 { get; set; }
        public string KeyValue6 { get; set; }
        public string KeyValue7 { get; set; }
        public string KeyValue8 { get; set; }
        public string KeyValue9 { get; set; }
        public string KeyValue10 { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    }
}
