//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkRTTemp
    {
        public long SPID { get; set; }
        public Nullable<long> MLCPlanSer { get; set; }
        public Nullable<double> IndexValues { get; set; }
        public Nullable<long> PointCount { get; set; }
        public Nullable<long> LeafNumber { get; set; }
        public Nullable<double> DynamicPosTolerance { get; set; }
        public Nullable<double> LeftLeafPosition { get; set; }
        public Nullable<double> RightLeafPosition { get; set; }
        public string UpdateFlag { get; set; }
        public Nullable<short> LeftLeaf { get; set; }
        public Nullable<short> RightLeaf { get; set; }
        public Nullable<long> AddOnSer { get; set; }
        public string AddOnId { get; set; }
        public Nullable<long> SlotSer { get; set; }
        public Nullable<long> SlotNo { get; set; }
        public Nullable<long> CacheKey { get; set; }
        public string PatientId { get; set; }
        public string CourseID { get; set; }
        public string PlanSetupID { get; set; }
        public string FieldID { get; set; }
        public string FieldName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string MachineId { get; set; }
        public string ToleranceId { get; set; }
        public string ToleranceTableName { get; set; }
        public string Scale { get; set; }
        public string TechniqueId { get; set; }
        public string EnergyMode { get; set; }
        public Nullable<int> MLCFlag { get; set; }
        public string SetupNote { get; set; }
        public string CollMode { get; set; }
        public Nullable<int> MU { get; set; }
        public Nullable<double> TreatmentTime { get; set; }
        public Nullable<double> SSD { get; set; }
        public Nullable<double> StopAng { get; set; }
        public string StopAngE { get; set; }
        public Nullable<double> MUdeg { get; set; }
        public Nullable<double> CollRtn { get; set; }
        public Nullable<double> CollRtnM { get; set; }
        public Nullable<double> GantryRtn { get; set; }
        public string GantryRtnE { get; set; }
        public string GantryRtnExt { get; set; }
        public Nullable<double> CollY1 { get; set; }
        public Nullable<double> CollY2 { get; set; }
        public Nullable<double> CollX1 { get; set; }
        public Nullable<double> CollX2 { get; set; }
        public Nullable<double> CouchVrt { get; set; }
        public Nullable<double> CouchVrtM { get; set; }
        public Nullable<double> CouchLng { get; set; }
        public Nullable<double> CouchLngM { get; set; }
        public Nullable<double> CouchLat { get; set; }
        public Nullable<double> CouchLatM { get; set; }
        public Nullable<double> CouchRtn { get; set; }
        public Nullable<double> CouchRtnM { get; set; }
        public string AddOnId1 { get; set; }
        public string AddOnType1 { get; set; }
        public string SlotName1 { get; set; }
        public string AddOnId2 { get; set; }
        public string AddOnType2 { get; set; }
        public string SlotName2 { get; set; }
        public string AddOnId3 { get; set; }
        public string AddOnType3 { get; set; }
        public string SlotName3 { get; set; }
        public string AddOnId4 { get; set; }
        public string AddOnType4 { get; set; }
        public string SlotName4 { get; set; }
        public string AddOnId5 { get; set; }
        public string AddOnType5 { get; set; }
        public string SlotName5 { get; set; }
        public string AddOnId6 { get; set; }
        public string AddOnType6 { get; set; }
        public string SlotName6 { get; set; }
        public Nullable<int> TreatmentFlag { get; set; }
        public Nullable<int> PtTreatedFlag { get; set; }
        public Nullable<int> DoseRate { get; set; }
        public Nullable<double> WedgeDose { get; set; }
        public Nullable<long> FieldSer { get; set; }
        public Nullable<long> FieldRevCount { get; set; }
        public Nullable<double> MUpGy { get; set; }
        public Nullable<double> TempDose { get; set; }
        public Nullable<int> WDProcessFlag { get; set; }
    }
}
