//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalizationJig
    {
        public long ResourceSer { get; set; }
        public string ImagingGeometry { get; set; }
        public string Beam1Label { get; set; }
        public Nullable<double> Beam1FocusToFilmDist { get; set; }
        public Nullable<double> Beam1IsocenterToFilmDist { get; set; }
        public Nullable<double> Beam1Angle { get; set; }
        public Nullable<double> Beam1FilmToJigDist { get; set; }
        public Nullable<double> Beam1JigSize { get; set; }
        public Nullable<double> Beam1JigCrossSize { get; set; }
        public Nullable<double> Beam1JigCrossAngle { get; set; }
        public Nullable<double> Beam1JigCrossShift { get; set; }
        public string Beam2Label { get; set; }
        public Nullable<double> Beam2FocusToFilmDist { get; set; }
        public Nullable<double> Beam2IsocenterToFilmDist { get; set; }
        public Nullable<double> Beam2Angle { get; set; }
        public Nullable<double> Beam2FilmToJigDist { get; set; }
        public Nullable<double> Beam2JigSize { get; set; }
        public Nullable<double> Beam2JigCrossSize { get; set; }
        public Nullable<double> Beam2JigCrossAngle { get; set; }
        public Nullable<double> Beam2JigCrossShift { get; set; }
        public byte[] Plane { get; set; }
        public int Beam1FocusToFilmDistFlag { get; set; }
        public int Beam2FocusToFilmDistFlag { get; set; }
    
        public virtual ImagingDevice ImagingDevice { get; set; }
    }
}
