//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupTable
    {
        public long LookupTableSer { get; set; }
        public string ListSelector { get; set; }
        public Nullable<long> SubSelector { get; set; }
        public string LanguageId { get; set; }
        public string LookupValue { get; set; }
        public string Expression1 { get; set; }
        public string Expression2 { get; set; }
        public string Expression3 { get; set; }
        public int EditFlag { get; set; }
        public int DefaultFlag { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual LanguageLookup LanguageLookup { get; set; }
    }
}
