//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Machine()
        {
            this.ChildMachines = new HashSet<ChildMachine>();
            this.ChildMachines1 = new HashSet<ChildMachine>();
            this.DeliverySetupDeviceMachines = new HashSet<DeliverySetupDeviceMachine>();
            this.OperatingLimits = new HashSet<OperatingLimit>();
            this.Series = new HashSet<Series>();
            this.Slice = new HashSet<Slouse>();
        }
    
        public long ResourceSer { get; set; }
        public Nullable<long> WorkstationSer { get; set; }
        public string MachineId { get; set; }
        public string MachineName { get; set; }
        public string MachineType { get; set; }
        public string MachineModel { get; set; }
        public string MachineInterface { get; set; }
        public string MachineScale { get; set; }
        public string ManufacturerName { get; set; }
        public string MachineSerialNo { get; set; }
        public string ServiceContact { get; set; }
        public Nullable<System.DateTime> DateInstalled { get; set; }
        public Nullable<System.DateTime> DateLastService { get; set; }
        public Nullable<System.DateTime> DateNextService { get; set; }
        public string OperationStatus { get; set; }
        public string SoftwareVersion { get; set; }
        public string HardwareVersion { get; set; }
        public string Description { get; set; }
        public string CharacterSet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildMachine> ChildMachines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildMachine> ChildMachines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliverySetupDeviceMachine> DeliverySetupDeviceMachines { get; set; }
        public virtual ImagingDevice ImagingDevice { get; set; }
        public virtual MillingMachine MillingMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatingLimit> OperatingLimits { get; set; }
        public virtual PatientSupportDevice PatientSupportDevice { get; set; }
        public virtual PlanningSystem PlanningSystem { get; set; }
        public virtual RadiationDevice RadiationDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Series> Series { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slouse> Slice { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Workstation Workstation { get; set; }
    }
}
