//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatchResult()
        {
            this.ImageMatchResults = new HashSet<ImageMatchResult>();
        }
    
        public long MatchResultSer { get; set; }
        public string MatchResultId { get; set; }
        public string MatchAlgorithm { get; set; }
        public byte[] MatchMatrix { get; set; }
        public string KindOfMatch { get; set; }
        public Nullable<double> MaxErrorDist { get; set; }
        public Nullable<double> AverageErrorDist { get; set; }
        public Nullable<double> ScaleFactor { get; set; }
        public string ModificationLog { get; set; }
        public string Comment { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageMatchResult> ImageMatchResults { get; set; }
    }
}
