//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLCLeaf
    {
        public long MLCLeafSer { get; set; }
        public long MLCBankSer { get; set; }
        public string LeafId { get; set; }
        public int LeafNumber { get; set; }
        public Nullable<double> OffsetY { get; set; }
        public Nullable<double> MaxRetractPosition { get; set; }
        public Nullable<double> MaxExtendPosition { get; set; }
        public double Width { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual MLCBank MLCBank { get; set; }
    }
}
