//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLCPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MLCPlan()
        {
            this.Matrices = new HashSet<Matrix>();
        }
    
        public long MLCPlanSer { get; set; }
        public long RadiationSer { get; set; }
        public string MLCPlanId { get; set; }
        public string MLCPlanName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationUserName { get; set; }
        public string MLCPlanType { get; set; }
        public string IndexParameterType { get; set; }
        public string Comment { get; set; }
        public int IsLockedFlag { get; set; }
        public int EllipticalMarginFlag { get; set; }
        public int BEVMarginFlag { get; set; }
        public Nullable<double> LeftMargin { get; set; }
        public Nullable<double> RightMargin { get; set; }
        public Nullable<double> TopMargin { get; set; }
        public Nullable<double> BottomMargin { get; set; }
        public string ContourMeetPoint { get; set; }
        public string ClosedMeetPoint { get; set; }
        public int OptimizeCollRtnFlag { get; set; }
        public Nullable<int> CollimatorJawOptimization { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public Nullable<double> FitMLCToBlockMargin { get; set; }
        public Nullable<short> FitMLCToBlockMarginMethod { get; set; }
    
        public virtual ExternalFieldCommon ExternalFieldCommon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matrix> Matrices { get; set; }
    }
}
