//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonScheduledActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NonScheduledActivity()
        {
            this.NonScheduledActivityMHs = new HashSet<NonScheduledActivityMH>();
        }
    
        public long NonScheduledActivitySer { get; set; }
        public int NonScheduledActivityRevCount { get; set; }
        public long ActivityInstanceSer { get; set; }
        public int ActivityInstanceRevCount { get; set; }
        public Nullable<long> PatientSer { get; set; }
        public Nullable<long> CreatedByResourceSer { get; set; }
        public string CreatedByUserName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string UID { get; set; }
        public string ObjectStatus { get; set; }
        public Nullable<System.DateTime> DueDateTime { get; set; }
        public string NonScheduledActivityCode { get; set; }
        public string Priority { get; set; }
        public string ActivityNote { get; set; }
        public Nullable<long> RecurrenceRuleSer { get; set; }
        public string ReadByAppUserName { get; set; }
        public Nullable<System.DateTime> ReadByDateTime { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public int WorkFlowActiveFlag { get; set; }
    
        public virtual ActivityInstance ActivityInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonScheduledActivityMH> NonScheduledActivityMHs { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual RecurrenceRule RecurrenceRule { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
