//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObsoleteObject
    {
        public long ObsoleteObjectSer { get; set; }
        public string DirLabel { get; set; }
        public string ObjectPath { get; set; }
        public string ErrorReason { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastAccessDate { get; set; }
        public Nullable<long> PatientSer { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
