//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRTStatu
    {
        public long PatientSer { get; set; }
        public string StatusType { get; set; }
        public string Status { get; set; }
        public string ObjectType { get; set; }
        public Nullable<System.DateTime> LastObjectDate { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
