//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayorAuthorization
    {
        public long PayorAuthorizationSer { get; set; }
        public long PayorSer { get; set; }
        public string Description { get; set; }
        public string AuthorizedBy { get; set; }
        public string AuthorizationPhone { get; set; }
        public string AuthorizationFAX { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual Payor Payor { get; set; }
    }
}
