//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfContact
    {
        public long PointOfContactSer { get; set; }
        public Nullable<long> AddressSer { get; set; }
        public long PatientSer { get; set; }
        public int PrimaryFlag { get; set; }
        public string Relationship { get; set; }
        public string Honorific { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NameSuffix { get; set; }
        public string FirstNameUpper { get; set; }
        public string LastNameUpper { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Sex { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhone { get; set; }
        public string Comment { get; set; }
        public string CreatedByHL7 { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
        public string MobilePhone { get; set; }
        public int EntrustedContactFlag { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
