//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionPropertyItem
    {
        public long PrescriptionPropertyItemSer { get; set; }
        public long PrescriptionPropertySer { get; set; }
        public short ItemType { get; set; }
        public string ItemValue { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual PrescriptionProperty PrescriptionProperty { get; set; }
    }
}
