//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionAnatomyItem
    {
        public long PrescriptionAnatomyItemSer { get; set; }
        public long PrescriptionAnatomySer { get; set; }
        public string ItemType { get; set; }
        public string ItemValue { get; set; }
        public string ItemValueUnit { get; set; }
        public string Param1Value { get; set; }
        public string Param1ValueUnit { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual PrescriptionAnatomy PrescriptionAnatomy { get; set; }
    }
}
