//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryFluenceMode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrimaryFluenceMode()
        {
            this.DemExternalBeams = new HashSet<DemExternalBeam>();
            this.DoseRates = new HashSet<DoseRate>();
            this.DosimetricDatas = new HashSet<DosimetricData>();
            this.OperatingLimits = new HashSet<OperatingLimit>();
        }
    
        public long AddOnSer { get; set; }
        public Nullable<double> MaxCollX { get; set; }
        public Nullable<double> MaxCollY { get; set; }
        public Nullable<double> MaxX1 { get; set; }
        public Nullable<double> MaxX2 { get; set; }
        public Nullable<double> MaxY1 { get; set; }
        public Nullable<double> MaxY2 { get; set; }
        public Nullable<double> MinCollX { get; set; }
        public Nullable<double> MinCollY { get; set; }
        public Nullable<double> MinX1 { get; set; }
        public Nullable<double> MinX2 { get; set; }
        public Nullable<double> MinY1 { get; set; }
        public Nullable<double> MinY2 { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemExternalBeam> DemExternalBeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoseRate> DoseRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DosimetricData> DosimetricDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatingLimit> OperatingLimits { get; set; }
    }
}
