//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangeShifter
    {
        public long AddOnSer { get; set; }
        public Nullable<double> IsoRangeShifterDist { get; set; }
        public string RangeShifterType { get; set; }
        public int MovesWithSnout { get; set; }
    
        public virtual AddOn AddOn { get; set; }
    }
}
