//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurrenceElement
    {
        public long RecurrenceElementSer { get; set; }
        public long RecurrenceRuleSer { get; set; }
        public int ElementType { get; set; }
        public int ElementValue { get; set; }
    
        public virtual RecurrenceRule RecurrenceRule { get; set; }
    }
}
