//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RefPoint()
        {
            this.BreakPoints = new HashSet<BreakPoint>();
            this.DoseContributions = new HashSet<DoseContribution>();
            this.RadiationRefPoints = new HashSet<RadiationRefPoint>();
            this.RefPointHstries = new HashSet<RefPointHstry>();
            this.RefPointLocations = new HashSet<RefPointLocation>();
            this.RefPointLogs = new HashSet<RefPointLog>();
        }
    
        public long RefPointSer { get; set; }
        public long PatientVolumeSer { get; set; }
        public long PatientSer { get; set; }
        public string RefPointId { get; set; }
        public string RefPointName { get; set; }
        public string RefPointUID { get; set; }
        public string RefPointType { get; set; }
        public Nullable<double> TotalDoseLimit { get; set; }
        public Nullable<double> DailyDoseLimit { get; set; }
        public Nullable<double> SessionDoseLimit { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BreakPoint> BreakPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoseContribution> DoseContributions { get; set; }
        public virtual PatientVolume PatientVolume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadiationRefPoint> RadiationRefPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefPointHstry> RefPointHstries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefPointLocation> RefPointLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefPointLog> RefPointLogs { get; set; }
    }
}
