//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceIdentifier
    {
        public long ResourceIdentifierSer { get; set; }
        public long ResourceSer { get; set; }
        public long ResourceIdentifierTypeSer { get; set; }
        public string KeyValue { get; set; }
        public string UpperKeyValue { get; set; }
        public int CurValueFlag { get; set; }
        public int ValidEntryFlag { get; set; }
        public System.DateTime EffDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual ResourceIdentifierType ResourceIdentifierType { get; set; }
    }
}
