//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResourceDepartment()
        {
            this.AvailPrefWeeklyPttrns = new HashSet<AvailPrefWeeklyPttrn>();
        }
    
        public long ResourceDepartmentSer { get; set; }
        public long DepartmentSer { get; set; }
        public long ResourceSer { get; set; }
        public int DefaultDepartment { get; set; }
        public int AssignedToDepartment { get; set; }
        public string AccessRights { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailPrefWeeklyPttrn> AvailPrefWeeklyPttrns { get; set; }
        public virtual Department Department { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
