//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceControl
    {
        public string ActivityName { get; set; }
        public System.DateTime ActivityDateTime { get; set; }
        public string Object { get; set; }
        public string ObjectName { get; set; }
        public string DeviceName { get; set; }
        public Nullable<int> BeforeSize { get; set; }
        public Nullable<int> AfterSize { get; set; }
        public Nullable<System.DateTime> BeforeTime { get; set; }
        public Nullable<System.DateTime> AfterTime { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
        public string Comment { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    }
}
