//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionProcedurePart
    {
        public long SessionProcedurePartSer { get; set; }
        public Nullable<long> RadiationSer { get; set; }
        public string ImageType { get; set; }
        public int SequenceNumber { get; set; }
        public Nullable<double> AcqAdjustment { get; set; }
        public int AutoSave { get; set; }
        public int DoseAccumulation { get; set; }
        public int Continuous { get; set; }
        public int BeamOff { get; set; }
        public int DeviationImage { get; set; }
        public Nullable<int> DevEnergy { get; set; }
        public Nullable<int> DevDoseRate { get; set; }
        public Nullable<int> DevGeometry { get; set; }
        public Nullable<double> JawState { get; set; }
        public Nullable<double> DevCollX1 { get; set; }
        public Nullable<double> DevCollX2 { get; set; }
        public Nullable<double> DevCollY1 { get; set; }
        public Nullable<double> DevCollY2 { get; set; }
        public Nullable<int> MUSubtraction { get; set; }
        public string AcquisitionMode { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
        public long SessionProcedureSer { get; set; }
        public string ImageModality { get; set; }
        public Nullable<long> RTPlanSer { get; set; }
    
        public virtual Radiation Radiation { get; set; }
        public virtual RTPlan RTPlan { get; set; }
        public virtual SessionProcedure SessionProcedure { get; set; }
    }
}
