//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionRTPlan
    {
        public long SessionRTPlanSer { get; set; }
        public long RTPlanSer { get; set; }
        public long SessionSer { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
        public string Status { get; set; }
    
        public virtual RTPlan RTPlan { get; set; }
        public virtual Session Session { get; set; }
    }
}
