//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionProcedure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionProcedure()
        {
            this.SessionProcedureParts = new HashSet<SessionProcedurePart>();
        }
    
        public long SessionProcedureSer { get; set; }
        public long SessionSer { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public long SeriesSer { get; set; }
        public Nullable<long> ProcedureItemSer { get; set; }
        public string ProcedureInstanceUID { get; set; }
        public string SessionProcedureTemplateId { get; set; }
        public string Status { get; set; }
        public double ProgressIndicator { get; set; }
        public string HstryUserName { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual ProcedureItem ProcedureItem { get; set; }
        public virtual Series Series { get; set; }
        public virtual Session Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionProcedurePart> SessionProcedureParts { get; set; }
    }
}
