//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slot()
        {
            this.FieldAddOns = new HashSet<FieldAddOn>();
            this.SlotAddOns = new HashSet<SlotAddOn>();
        }
    
        public long SlotSer { get; set; }
        public long ResourceSer { get; set; }
        public int SlotNumber { get; set; }
        public string SlotName { get; set; }
        public string Comment { get; set; }
        public Nullable<int> InternalCode { get; set; }
        public Nullable<double> SourceSlotDist { get; set; }
        public Nullable<double> MaxCompThickness { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldAddOn> FieldAddOns { get; set; }
        public virtual RadiationDevice RadiationDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlotAddOn> SlotAddOns { get; set; }
    }
}
