//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateCycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateCycle()
        {
            this.ActivityInstances = new HashSet<ActivityInstance>();
            this.TemplateCycleMHs = new HashSet<TemplateCycleMH>();
        }
    
        public long TemplateCycleSer { get; set; }
        public int TemplateCycleRevCount { get; set; }
        public long TemplateSer { get; set; }
        public int TemplateRevCount { get; set; }
        public string ObjectStatus { get; set; }
        public long CycleSer { get; set; }
        public string Comment { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityInstance> ActivityInstances { get; set; }
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateCycleMH> TemplateCycleMHs { get; set; }
        public virtual TreatmentCycle TreatmentCycle { get; set; }
    }
}
