//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_DoseRefPoint
    {
        public long PatientSer { get; set; }
        public Nullable<long> RefPointSer { get; set; }
        public Nullable<double> DosePredicted { get; set; }
        public Nullable<double> DoseDelivered { get; set; }
        public Nullable<double> DoseCorrection { get; set; }
        public Nullable<double> DoseRemaining { get; set; }
        public Nullable<int> SessionsRemainingPrimary { get; set; }
        public Nullable<int> SessionsRemainingAny { get; set; }
    }
}
