//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_DoseFiguresApp
    {
        public long PatientSer { get; set; }
        public long CourseSer { get; set; }
        public long PlanSetupSer { get; set; }
        public long RTPlanSer { get; set; }
        public string PlanUID { get; set; }
        public Nullable<int> RTPlanAge { get; set; }
        public long FirstRTPlanSer { get; set; }
        public Nullable<long> RefPointSer { get; set; }
        public Nullable<int> PrimaryFlag { get; set; }
        public int FractionsPlanned { get; set; }
        public int FractionsDelivered { get; set; }
        public int FractionsRemaining { get; set; }
        public Nullable<double> DosePerFraction { get; set; }
        public Nullable<double> DoseDelivered { get; set; }
        public Nullable<double> DoseRemainingInFraction { get; set; }
        public Nullable<int> RunningPartial { get; set; }
        public Nullable<double> DoseRemainingMax { get; set; }
        public Nullable<double> DoseRemainingMin { get; set; }
        public Nullable<double> DoseRemaining { get; set; }
        public Nullable<double> DosePredictedMax { get; set; }
        public Nullable<double> DosePredictedMin { get; set; }
        public Nullable<double> DosePredicted { get; set; }
        public int TreatmentVisits { get; set; }
        public int CorrelatedEventsAll { get; set; }
        public int CorrelatedEventsPartial { get; set; }
        public int CorrelatedEventsCompleted { get; set; }
        public int SessionsRemaining { get; set; }
    }
}
