//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_TRTHistoryRecords
    {
        public long PatientSer { get; set; }
        public long CourseSer { get; set; }
        public long RTPlanSer { get; set; }
        public long RadiationSer { get; set; }
        public long RadiationHstrySer { get; set; }
        public Nullable<System.DateTime> TreatmentStartTime { get; set; }
        public Nullable<int> FractionNumber { get; set; }
        public Nullable<double> RecordMUActual { get; set; }
        public Nullable<double> FieldMUActual { get; set; }
        public Nullable<double> FieldMUPlanned { get; set; }
        public Nullable<int> EventNumber { get; set; }
        public Nullable<int> CorrelatedEventNumber { get; set; }
        public string RecordStatus { get; set; }
        public string FieldStatus { get; set; }
        public string TreatmentDeliveryType { get; set; }
    }
}
