//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickerMessageChannel
    {
        public long TickerMessageChannelSer { get; set; }
        public long TickerMessageSer { get; set; }
        public long TickerChannelSer { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual TickerChannel TickerChannel { get; set; }
        public virtual TickerMessage TickerMessage { get; set; }
    }
}
