//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrackingInformation()
        {
            this.DCObjectTrackingInfoes = new HashSet<DCObjectTrackingInfo>();
        }
    
        public long TrackingInformationSer { get; set; }
        public long PatientSer { get; set; }
        public long ArchiveLocationSer { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public string ArchiveUser { get; set; }
        public string ArchiveNote { get; set; }
        public Nullable<System.DateTime> PurgeDate { get; set; }
        public string PurgeUser { get; set; }
        public Nullable<System.DateTime> RestoreDate { get; set; }
        public string RestoreUser { get; set; }
        public string RestoreNote { get; set; }
        public Nullable<System.DateTime> RemoveDate { get; set; }
        public string RemoveUser { get; set; }
        public string ObjectStatus { get; set; }
        public string LTArchiveVersion { get; set; }
        public string DocDeleteStatus { get; set; }
        public string SchChrgDeleteStatus { get; set; }
        public string TrackingStatus { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual ArchiveLocation ArchiveLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCObjectTrackingInfo> DCObjectTrackingInfoes { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
