//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolOptConstraint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VolOptConstraint()
        {
            this.VolOptMatrices = new HashSet<VolOptMatrix>();
            this.VolOptStructs = new HashSet<VolOptStruct>();
        }
    
        public long VolOptConstraintsSer { get; set; }
        public long PlanSetupSer { get; set; }
        public string VolOptConstraintsId { get; set; }
        public string VolOptConstraintsName { get; set; }
        public string Comment { get; set; }
        public string Parameters { get; set; }
        public int ParametersLen { get; set; }
        public string ConstraintsType { get; set; }
        public string HstryUserName { get; set; }
        public byte[] HstryTimeStamp { get; set; }
        public System.DateTime HstryDateTime { get; set; }
        public string HstryTaskName { get; set; }
    
        public virtual PlanSetup PlanSetup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolOptMatrix> VolOptMatrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolOptStruct> VolOptStructs { get; set; }
    }
}
